version: '3.8'
services:
  kuyil-alpine:
    build:
      context: .
      target: runtime-alpine
    container_name: kuyil_alpine
    working_dir: /app
    command: ["./kuyil", "examples/simple_working.kyl"]
    volumes:
      - ./examples:/app/examples
      - ./unittest:/app/unittest
    tty: true

  kuyil-ubuntu:
    build:
      context: .
      target: runtime-ubuntu
    container_name: kuyil_ubuntu
    working_dir: /app
    command: ["./kuyil", "examples/simple_working.kyl"]
    volumes:
      - ./examples:/app/examples
      - ./unittest:/app/unittest
    tty: true
