SUBDIRS = math str http datetime fileio

.PHONY: all clean $(SUBDIRS)

all: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C shared_libs/$@

clean:
	for dir in $(SUBDIRS); do \
		$(MAKE) -C shared_libs/$$dir clean; \
	done
	rm -f libs/*.so
